// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
insert into api_keys (project_id, name, key_prefix, key_hash, scope)
values ($1, $2, $3, $4, $5)
returning id, project_id, name, key_prefix, key_hash, scope, created_at, last_used_at, revoked_at, expires_at
`

type CreateAPIKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	KeyPrefix string      `json:"key_prefix"`
	KeyHash   string      `json:"key_hash"`
	Scope     string      `json:"scope"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scope,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
select ak.id, ak.project_id, ak.name, ak.key_prefix, ak.key_hash, ak.scope, ak.created_at, ak.last_used_at, ak.revoked_at, ak.expires_at from api_keys ak
join projects p on p.id = ak.project_id
where ak.key_hash = $1
  and ak.revoked_at is null
  and (ak.expires_at is null or ak.expires_at > now())
  and p.status = 'active'
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
select id, project_id, name, key_prefix, key_hash, scope, created_at, last_used_at, revoked_at, expires_at from api_keys where project_id = $1 order by created_at desc
`

func (q *Queries) ListAPIKeysByProject(ctx context.Context, projectID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
update api_keys set revoked_at = now() where id = $1 and project_id = $2
`

type RevokeAPIKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
update api_keys set last_used_at = now() where id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
