// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDevicesByIDs = `-- name: GetDevicesByIDs :many
select id, project_id, token, platform, provider_type, status, metadata, created_at, updated_at from devices where project_id = $1 and id = any($2::uuid[])
`

type GetDevicesByIDsParams struct {
	ProjectID pgtype.UUID   `json:"project_id"`
	Ids       []pgtype.UUID `json:"ids"`
}

func (q *Queries) GetDevicesByIDs(ctx context.Context, arg GetDevicesByIDsParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Token,
			&i.Platform,
			&i.ProviderType,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceStatus = `-- name: MarkDeviceStatus :exec
update devices set status = $2, updated_at = now() where id = $1
`

type MarkDeviceStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) MarkDeviceStatus(ctx context.Context, arg MarkDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, markDeviceStatus, arg.ID, arg.Status)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
insert into devices (project_id, token, platform, provider_type, metadata)
values ($1, $2, $3, $4, $5)
on conflict (project_id, token) do update set
    platform = excluded.platform,
    provider_type = excluded.provider_type,
    metadata = excluded.metadata,
    status = 'active',
    updated_at = now()
returning id, project_id, token, platform, provider_type, status, metadata, created_at, updated_at
`

type UpsertDeviceParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	Token        string      `json:"token"`
	Platform     string      `json:"platform"`
	ProviderType string      `json:"provider_type"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ProjectID,
		arg.Token,
		arg.Platform,
		arg.ProviderType,
		arg.Metadata,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Token,
		&i.Platform,
		&i.ProviderType,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
