// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDevicesByIDs = `-- name: GetDevicesByIDs :many
select id, project_id, subscriber_id, token, platform, provider_type, status, metadata, created_at, updated_at from devices where project_id = $1 and id = any($2::uuid[])
`

type GetDevicesByIDsParams struct {
	ProjectID pgtype.UUID   `json:"project_id"`
	Ids       []pgtype.UUID `json:"ids"`
}

func (q *Queries) GetDevicesByIDs(ctx context.Context, arg GetDevicesByIDsParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriberID,
			&i.Token,
			&i.Platform,
			&i.ProviderType,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByProject = `-- name: ListDevicesByProject :many
select d.id, d.project_id, d.token, d.platform, d.provider_type, d.status,
    d.metadata, d.created_at, d.updated_at, d.subscriber_id,
    coalesce(s.external_id, '') as external_id
from devices d
left join subscribers s on s.id = d.subscriber_id
where d.project_id = $1
  and ($2::text = '' or s.external_id = $2::text)
  and ($3::text = '' or d.status = $3::text)
order by d.created_at desc
limit $5::int offset $4::int
`

type ListDevicesByProjectParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	ExternalID string      `json:"external_id"`
	Status     string      `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListDevicesByProjectRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Token        string             `json:"token"`
	Platform     string             `json:"platform"`
	ProviderType string             `json:"provider_type"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SubscriberID pgtype.UUID        `json:"subscriber_id"`
	ExternalID   string             `json:"external_id"`
}

// external_id/status filters are skipped when passed as an empty string.
func (q *Queries) ListDevicesByProject(ctx context.Context, arg ListDevicesByProjectParams) ([]ListDevicesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByProject,
		arg.ProjectID,
		arg.ExternalID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesByProjectRow
	for rows.Next() {
		var i ListDevicesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Token,
			&i.Platform,
			&i.ProviderType,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubscriberID,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceStatus = `-- name: MarkDeviceStatus :exec
update devices set status = $2, updated_at = now() where id = $1
`

type MarkDeviceStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) MarkDeviceStatus(ctx context.Context, arg MarkDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, markDeviceStatus, arg.ID, arg.Status)
	return err
}

const markStaleDevicesByDeviceUUID = `-- name: MarkStaleDevicesByDeviceUUID :many
update devices
set status = 'stale', updated_at = now()
where project_id = $1
  and subscriber_id = $2
  and id != $3
  and status = 'active'
  and metadata ->> 'device_uuid' = $4::text
returning id, project_id, subscriber_id, token, platform, provider_type, status, metadata, created_at, updated_at
`

type MarkStaleDevicesByDeviceUUIDParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
	ID           pgtype.UUID `json:"id"`
	DeviceUuid   string      `json:"device_uuid"`
}

// Marks stale every other active device under the same subscriber that
// shares the given device_uuid, excluding the device row just registered.
func (q *Queries) MarkStaleDevicesByDeviceUUID(ctx context.Context, arg MarkStaleDevicesByDeviceUUIDParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, markStaleDevicesByDeviceUUID,
		arg.ProjectID,
		arg.SubscriberID,
		arg.ID,
		arg.DeviceUuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriberID,
			&i.Token,
			&i.Platform,
			&i.ProviderType,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
insert into devices (project_id, token, platform, provider_type, metadata, subscriber_id)
values ($1, $2, $3, $4, $5, $6)
on conflict (project_id, token) do update set
    platform = excluded.platform,
    provider_type = excluded.provider_type,
    metadata = excluded.metadata,
    subscriber_id = coalesce(excluded.subscriber_id, devices.subscriber_id),
    status = 'active',
    updated_at = now()
returning id, project_id, subscriber_id, token, platform, provider_type, status, metadata, created_at, updated_at
`

type UpsertDeviceParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	Token        string      `json:"token"`
	Platform     string      `json:"platform"`
	ProviderType string      `json:"provider_type"`
	Metadata     []byte      `json:"metadata"`
	SubscriberID pgtype.UUID `json:"subscriber_id"`
}

// subscriber_id keeps its existing value when omitted.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ProjectID,
		arg.Token,
		arg.Platform,
		arg.ProviderType,
		arg.Metadata,
		arg.SubscriberID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriberID,
		&i.Token,
		&i.Platform,
		&i.ProviderType,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
