// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	Scope      string             `json:"scope"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

type Device struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	SubscriberID pgtype.UUID        `json:"subscriber_id"`
	Token        string             `json:"token"`
	Platform     string             `json:"platform"`
	ProviderType string             `json:"provider_type"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IdempotencyKey  *string            `json:"idempotency_key"`
	Title           *string            `json:"title"`
	Body            *string            `json:"body"`
	Data            []byte             `json:"data"`
	TargetSpec      []byte             `json:"target_spec"`
	Status          string             `json:"status"`
	TotalRecipients int32              `json:"total_recipients"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type NotificationRecipient struct {
	ID                pgtype.UUID        `json:"id"`
	NotificationID    pgtype.UUID        `json:"notification_id"`
	DeviceID          pgtype.UUID        `json:"device_id"`
	ProviderType      string             `json:"provider_type"`
	Status            string             `json:"status"`
	ProviderMessageID *string            `json:"provider_message_id"`
	ErrorCode         *string            `json:"error_code"`
	ErrorMessage      *string            `json:"error_message"`
	AttemptCount      int32              `json:"attempt_count"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	FailedAt          pgtype.Timestamptz `json:"failed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProviderCredential struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ProviderType string             `json:"provider_type"`
	Environment  string             `json:"environment"`
	Credential   []byte             `json:"credential"`
	WrappedDek   []byte             `json:"wrapped_dek"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Subscriber struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	ExternalID string             `json:"external_id"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
