// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeNotification = `-- name: CompleteNotification :exec
update notifications set status = $2, completed_at = now() where id = $1
`

type CompleteNotificationParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) CompleteNotification(ctx context.Context, arg CompleteNotificationParams) error {
	_, err := q.db.Exec(ctx, completeNotification, arg.ID, arg.Status)
	return err
}

const createNotification = `-- name: CreateNotification :one
insert into notifications (project_id, idempotency_key, title, body, data, target_spec)
values ($1, $2, $3, $4, $5, $6)
returning id, project_id, idempotency_key, title, body, data, target_spec, status, total_recipients, created_at, completed_at
`

type CreateNotificationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
	Title          *string     `json:"title"`
	Body           *string     `json:"body"`
	Data           []byte      `json:"data"`
	TargetSpec     []byte      `json:"target_spec"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.TargetSpec,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.TargetSpec,
		&i.Status,
		&i.TotalRecipients,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
select id, project_id, idempotency_key, title, body, data, target_spec, status, total_recipients, created_at, completed_at from notifications where id = $1 and project_id = $2
`

type GetNotificationParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.ProjectID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.TargetSpec,
		&i.Status,
		&i.TotalRecipients,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
select id, project_id, idempotency_key, title, body, data, target_spec, status, total_recipients, created_at, completed_at from notifications where id = $1
`

// Unscoped by project: only for the dashboard, which is visible to every
// project by design (see internal/dashboard's visibleProjects).
func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.TargetSpec,
		&i.Status,
		&i.TotalRecipients,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getNotificationByIdempotencyKey = `-- name: GetNotificationByIdempotencyKey :one
select id, project_id, idempotency_key, title, body, data, target_spec, status, total_recipients, created_at, completed_at from notifications where project_id = $1 and idempotency_key = $2
`

type GetNotificationByIdempotencyKeyParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

func (q *Queries) GetNotificationByIdempotencyKey(ctx context.Context, arg GetNotificationByIdempotencyKeyParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.TargetSpec,
		&i.Status,
		&i.TotalRecipients,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listNotificationsByProject = `-- name: ListNotificationsByProject :many
select id, project_id, idempotency_key, title, body, data, target_spec, status, total_recipients, created_at, completed_at from notifications
where project_id = $1
order by created_at desc
limit $3::int offset $2::int
`

type ListNotificationsByProjectParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListNotificationsByProject(ctx context.Context, arg ListNotificationsByProjectParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByProject, arg.ProjectID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IdempotencyKey,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.TargetSpec,
			&i.Status,
			&i.TotalRecipients,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotificationStatus = `-- name: SetNotificationStatus :exec
update notifications set status = $2 where id = $1
`

type SetNotificationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetNotificationStatus(ctx context.Context, arg SetNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, setNotificationStatus, arg.ID, arg.Status)
	return err
}

const setNotificationTotals = `-- name: SetNotificationTotals :exec
update notifications set total_recipients = $2 where id = $1
`

type SetNotificationTotalsParams struct {
	ID              pgtype.UUID `json:"id"`
	TotalRecipients int32       `json:"total_recipients"`
}

func (q *Queries) SetNotificationTotals(ctx context.Context, arg SetNotificationTotalsParams) error {
	_, err := q.db.Exec(ctx, setNotificationTotals, arg.ID, arg.TotalRecipients)
	return err
}
