// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_credentials.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveProviderCredential = `-- name: GetActiveProviderCredential :one
select id, project_id, provider_type, environment, credential, is_active, created_at, updated_at from provider_credentials
where project_id = $1 and provider_type = $2 and environment = $3 and is_active
limit 1
`

type GetActiveProviderCredentialParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	ProviderType string      `json:"provider_type"`
	Environment  string      `json:"environment"`
}

func (q *Queries) GetActiveProviderCredential(ctx context.Context, arg GetActiveProviderCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, getActiveProviderCredential, arg.ProjectID, arg.ProviderType, arg.Environment)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProviderType,
		&i.Environment,
		&i.Credential,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProviderCredential = `-- name: UpsertProviderCredential :one
insert into provider_credentials (project_id, provider_type, environment, credential)
values ($1, $2, $3, $4)
on conflict (project_id, provider_type, environment) do update set
    credential = excluded.credential,
    is_active = true,
    updated_at = now()
returning id, project_id, provider_type, environment, credential, is_active, created_at, updated_at
`

type UpsertProviderCredentialParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	ProviderType string      `json:"provider_type"`
	Environment  string      `json:"environment"`
	Credential   []byte      `json:"credential"`
}

func (q *Queries) UpsertProviderCredential(ctx context.Context, arg UpsertProviderCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, upsertProviderCredential,
		arg.ProjectID,
		arg.ProviderType,
		arg.Environment,
		arg.Credential,
	)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProviderType,
		&i.Environment,
		&i.Credential,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
