// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_credentials.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveProviderCredential = `-- name: GetActiveProviderCredential :one
select id, project_id, provider_type, environment, credential, is_active, created_at, updated_at, wrapped_dek from provider_credentials
where project_id = $1 and provider_type = $2 and environment = $3 and is_active
limit 1
`

type GetActiveProviderCredentialParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	ProviderType string      `json:"provider_type"`
	Environment  string      `json:"environment"`
}

func (q *Queries) GetActiveProviderCredential(ctx context.Context, arg GetActiveProviderCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, getActiveProviderCredential, arg.ProjectID, arg.ProviderType, arg.Environment)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProviderType,
		&i.Environment,
		&i.Credential,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WrappedDek,
	)
	return i, err
}

const listProviderCredentialsByProject = `-- name: ListProviderCredentialsByProject :many
select id, project_id, provider_type, environment, is_active, created_at, updated_at
from provider_credentials
where project_id = $1
order by provider_type
`

type ListProviderCredentialsByProjectRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ProviderType string             `json:"provider_type"`
	Environment  string             `json:"environment"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Never selects credential/wrapped_dek: this feeds the dashboard, which
// must never see ciphertext or key material.
func (q *Queries) ListProviderCredentialsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListProviderCredentialsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listProviderCredentialsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderCredentialsByProjectRow
	for rows.Next() {
		var i ListProviderCredentialsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProviderType,
			&i.Environment,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderCredential = `-- name: UpsertProviderCredential :one
insert into provider_credentials (project_id, provider_type, environment, credential, wrapped_dek)
values ($1, $2, $3, $4, $5)
on conflict (project_id, provider_type, environment) do update set
    credential = excluded.credential,
    wrapped_dek = excluded.wrapped_dek,
    is_active = true,
    updated_at = now()
returning id, project_id, provider_type, environment, credential, is_active, created_at, updated_at, wrapped_dek
`

type UpsertProviderCredentialParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	ProviderType string      `json:"provider_type"`
	Environment  string      `json:"environment"`
	Credential   []byte      `json:"credential"`
	WrappedDek   []byte      `json:"wrapped_dek"`
}

func (q *Queries) UpsertProviderCredential(ctx context.Context, arg UpsertProviderCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, upsertProviderCredential,
		arg.ProjectID,
		arg.ProviderType,
		arg.Environment,
		arg.Credential,
		arg.WrappedDek,
	)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProviderType,
		&i.Environment,
		&i.Credential,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WrappedDek,
	)
	return i, err
}
