// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipients.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecipientStatuses = `-- name: CountRecipientStatuses :many
select status, count(*) as count from notification_recipients where notification_id = $1 group by status
`

type CountRecipientStatusesRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountRecipientStatuses(ctx context.Context, notificationID pgtype.UUID) ([]CountRecipientStatusesRow, error) {
	rows, err := q.db.Query(ctx, countRecipientStatuses, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRecipientStatusesRow
	for rows.Next() {
		var i CountRecipientStatusesRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationRecipient = `-- name: GetNotificationRecipient :one
select id, notification_id, device_id, provider_type, status, provider_message_id, error_code, error_message, attempt_count, sent_at, failed_at, created_at from notification_recipients where id = $1
`

func (q *Queries) GetNotificationRecipient(ctx context.Context, id pgtype.UUID) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, getNotificationRecipient, id)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.DeviceID,
		&i.ProviderType,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.SentAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipientByNotificationAndDevice = `-- name: GetRecipientByNotificationAndDevice :one
select id, notification_id, device_id, provider_type, status, provider_message_id, error_code, error_message, attempt_count, sent_at, failed_at, created_at from notification_recipients where notification_id = $1 and device_id = $2
`

type GetRecipientByNotificationAndDeviceParams struct {
	NotificationID pgtype.UUID `json:"notification_id"`
	DeviceID       pgtype.UUID `json:"device_id"`
}

func (q *Queries) GetRecipientByNotificationAndDevice(ctx context.Context, arg GetRecipientByNotificationAndDeviceParams) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, getRecipientByNotificationAndDevice, arg.NotificationID, arg.DeviceID)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.DeviceID,
		&i.ProviderType,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.SentAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotificationRecipient = `-- name: InsertNotificationRecipient :one
insert into notification_recipients (notification_id, device_id, provider_type)
values ($1, $2, $3)
on conflict (notification_id, device_id) do nothing
returning id, notification_id, device_id, provider_type, status, provider_message_id, error_code, error_message, attempt_count, sent_at, failed_at, created_at
`

type InsertNotificationRecipientParams struct {
	NotificationID pgtype.UUID `json:"notification_id"`
	DeviceID       pgtype.UUID `json:"device_id"`
	ProviderType   string      `json:"provider_type"`
}

func (q *Queries) InsertNotificationRecipient(ctx context.Context, arg InsertNotificationRecipientParams) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, insertNotificationRecipient, arg.NotificationID, arg.DeviceID, arg.ProviderType)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.DeviceID,
		&i.ProviderType,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.SentAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationRecipients = `-- name: ListNotificationRecipients :many
select nr.id, nr.notification_id, nr.device_id, nr.provider_type, nr.status, nr.provider_message_id, nr.error_code, nr.error_message, nr.attempt_count, nr.sent_at, nr.failed_at, nr.created_at from notification_recipients nr
join notifications n on n.id = nr.notification_id
where nr.notification_id = $1 and n.project_id = $2
order by nr.created_at
`

type ListNotificationRecipientsParams struct {
	NotificationID pgtype.UUID `json:"notification_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
}

func (q *Queries) ListNotificationRecipients(ctx context.Context, arg ListNotificationRecipientsParams) ([]NotificationRecipient, error) {
	rows, err := q.db.Query(ctx, listNotificationRecipients, arg.NotificationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationRecipient
	for rows.Next() {
		var i NotificationRecipient
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.DeviceID,
			&i.ProviderType,
			&i.Status,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.AttemptCount,
			&i.SentAt,
			&i.FailedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecipientFailed = `-- name: MarkRecipientFailed :exec
update notification_recipients
set status = 'failed', error_code = $2, error_message = $3, failed_at = now()
where id = $1
`

type MarkRecipientFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorCode    *string     `json:"error_code"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) MarkRecipientFailed(ctx context.Context, arg MarkRecipientFailedParams) error {
	_, err := q.db.Exec(ctx, markRecipientFailed, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	return err
}

const markRecipientSending = `-- name: MarkRecipientSending :one
update notification_recipients
set status = 'sending', attempt_count = attempt_count + 1
where id = $1
returning id, notification_id, device_id, provider_type, status, provider_message_id, error_code, error_message, attempt_count, sent_at, failed_at, created_at
`

func (q *Queries) MarkRecipientSending(ctx context.Context, id pgtype.UUID) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, markRecipientSending, id)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.DeviceID,
		&i.ProviderType,
		&i.Status,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.SentAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markRecipientSent = `-- name: MarkRecipientSent :exec
update notification_recipients
set status = 'sent', provider_message_id = $2, sent_at = now()
where id = $1
`

type MarkRecipientSentParams struct {
	ID                pgtype.UUID `json:"id"`
	ProviderMessageID *string     `json:"provider_message_id"`
}

func (q *Queries) MarkRecipientSent(ctx context.Context, arg MarkRecipientSentParams) error {
	_, err := q.db.Exec(ctx, markRecipientSent, arg.ID, arg.ProviderMessageID)
	return err
}
