// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into sessions (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, user_id, token_hash, created_at, last_used_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveSessionByHash = `-- name: GetActiveSessionByHash :one
select id, user_id, token_hash, created_at, last_used_at, expires_at, revoked_at from sessions
where token_hash = $1
  and revoked_at is null
  and expires_at > now()
`

func (q *Queries) GetActiveSessionByHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
update sessions set revoked_at = now() where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSessionLastUsed = `-- name: TouchSessionLastUsed :exec
update sessions set last_used_at = now() where id = $1
`

func (q *Queries) TouchSessionLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSessionLastUsed, id)
	return err
}
