// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveDevicesBySubscriberExternalIDs = `-- name: GetActiveDevicesBySubscriberExternalIDs :many
select d.id, d.project_id, d.token, d.platform, d.provider_type, d.status, d.metadata, d.created_at, d.updated_at, d.subscriber_id from devices d
join subscribers s on s.id = d.subscriber_id
where s.project_id = $1
  and s.external_id = any($2::text[])
  and s.status = 'subscribed'
  and d.status = 'active'
`

type GetActiveDevicesBySubscriberExternalIDsParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	ExternalIds []string    `json:"external_ids"`
}

// Active devices under subscribed subscribers matching any of the given
// external ids, scoped to the project.
func (q *Queries) GetActiveDevicesBySubscriberExternalIDs(ctx context.Context, arg GetActiveDevicesBySubscriberExternalIDsParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, getActiveDevicesBySubscriberExternalIDs, arg.ProjectID, arg.ExternalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Token,
			&i.Platform,
			&i.ProviderType,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubscriberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscriber = `-- name: UpsertSubscriber :one
insert into subscribers (project_id, external_id)
values ($1, $2)
on conflict (project_id, external_id) do update set
    last_seen_at = now()
returning id, project_id, external_id, status, created_at, last_seen_at
`

type UpsertSubscriberParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	ExternalID string      `json:"external_id"`
}

func (q *Queries) UpsertSubscriber(ctx context.Context, arg UpsertSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, upsertSubscriber, arg.ProjectID, arg.ExternalID)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalID,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
